drop table if exists ANT_PLAN_TEAM_GUIDE;

/*==============================================================*/
/* Table: ANT_PLAN_TEAM_GUIDE                                   */
/*==============================================================*/
create table ANT_PLAN_TEAM_GUIDE
(
   ID                   bigint not null auto_increment comment '主键',
   APPLICATION_CODE     varchar(50) comment '申请编码',
   SCHEDULE_CODE        varchar(50) comment '班期编码',
   CATEGORY             integer comment '申请导领类型 1-领队占位 2-领队不占位 3-跟团占位 4-跟团不占位 5-送团人员 6-接团人员',
   APPLICATION_ORDER    integer comment '申请排序',
   RELATION_TOURIST     text comment '关联游客 JSON',
   TITLE                varchar(1000) comment '标题',
   ESTIMATE_BEGIN_TIME  datetime comment '预计上团-时间',
   ESTIMATE_BEGIN_CITY  varchar(500) comment '预计上团-出发城市',
   ESTIMATE_BEGIN_ADDRESS varchar(1000) comment '预计上团-具体地址',
   ESTIMATE_END_TIME    datetime comment '预计下团-时间',
   ESTIMATE_END_ADDRESS varchar(1000) comment '预计下团-具体地址',
   SUBSIDY_AMOUNT       decimal(15,2) comment '出团补贴金额',
   SUBSIDY_REMARK       varchar(1000) comment '出团补贴备注',
   TURN_AMOUNT          decimal(15,2) comment '余额上交金额',
   TURN_REMARK          varchar(1000) comment '余额上交备注',
   TEAM_CATEGORY        text comment '团组类型 1-散拼 2-整团3-常规团 4-纯玩团 5-系列团 6-疗养团',
   GUIDE_QUALIFICATION  text comment '导游资质',
   CUSTOMER_COMPOSITION text comment '客户组成 1-代理为主 2-门店为主3-直销为主 4-教育|医疗|同行 5-VIP',
   REQUIRE_GENDER       integer comment '要求性别 0-未指定 1-男 2-女',
   GUIDE_SKILL          text comment '特点',
   REQUIRE_OTHER        text comment '其他要求',
   VISA_NOT_OCCUPY_DATE integer comment '护照-是否不占用证照日期 0(false)-否 1(true)-是',
   VISA_SIGN_OCCUPY_DATE integer comment '护照-是否送签占用证照日期 0(false)-否 1(true)-是',
   VISA_SIGN_DATE_FROM  datetime comment '护照-送签占用时间-开始',
   VISA_SIGN_DATE_TO    datetime comment '护照-送签占用时间-结束',
   VISA_PIN_OCCUPY_DATE integer comment '护照销签-是否占用证照日期 0(false)-否 1(true)-是',
   VISA_PIN_DATE_FROM   datetime comment '护照-销签占用时间-开始',
   VISA_PIN_DATE_TO     datetime comment '护照-销签占用时间-结束',
   VISA_REMARK          text comment '护照-备注',
   VISA_SELF            varchar(500) comment '领队自备签',
   VISA_SELF_LATER_DATE datetime comment '领队自备签-有效期晚于',
   VISA_SELF_ENTRY_TIMES integer comment '入境次数-大于等于',
   VISA_SELF_STAY_TIMES integer comment '签证停留次数',
   APPLICATION_ID       varchar(50) comment '申请人',
   APPLICATION_TIME     datetime comment '申请时间',
   SEND_GUIDE           varchar(50) comment '确定导游',
   SEND_ESTIMATE_BEGIN_TIME datetime comment '确定-预计上团-时间',
   SEND_ESTIMATE_BEGIN_CITY varchar(500) comment '派遣-预计上团-出发城市',
   SEND_ESTIMATE_BEGIN_ADDRESS varchar(1000) comment '派遣-预计上团-具体地址',
   SEND_ESTIMATE_END_TIME datetime comment '派遣-预计下团-时间',
   SEND_ESTIMATE_END_ADDRESS varchar(1000) comment '派遣-预计下团-具体地址',
   SEND_VISA_NOT_OCCUPY_DATE integer comment '派遣-护照-是否不占用证照日期 0(false)-否 1(true)-是',
   SEND_VISA_SIGN_OCCUPY_DATE integer comment '派遣-护照-是否送签占用证照日期 0(false)-否 1(true)-是',
   SEND_VISA_SIGN_DATE_FROM datetime comment '派遣-护照-送签占用时间-开始',
   SEND_VISA_SIGN_DATE_TO datetime comment '派遣-护照-送签占用时间-结束',
   SEND_VISA_PIN_OCCUPY_DATE integer comment '派遣-护照销签-是否占用证照日期 0(false)-否 1(true)-是',
   SEND_VISA_PIN_DATE_FROM datetime comment '派遣-护照-销签占用时间-开始',
   SEND_VISA_PIN_DATE_TO datetime comment '派遣-护照-销签占用时间-结束',
   SEND_VISA_REMARK     text comment '派遣-护照-备注',
   SEND_VISA_SELF       varchar(500) comment '派遣-领队自备签',
   SEND_VISA_SELF_LATER_DATE datetime comment '派遣-领队自备签-有效期晚于',
   SEND_VISA_SELF_ENTRY_TIMES integer comment '派遣-入境次数',
   SEND_VISA_SELF_STAY_TIMES integer comment '派遣-签证停留次数',
   SEND_VISA_SELF_REMARK text comment '派遣-自备签-备注',
   SEND_ID              varchar(50) comment '派遣人',
   SEND_TIME            datetime comment '派遣时间',
   CREATE_TIME          datetime comment '创建时间',
   CREATE_ID            varchar(50) comment '创建者',
   MODIFY_TIME          datetime comment '修改时间',
   MODIFY_ID            varchar(50) comment '修改者',
   DELETE_FLAG          char comment '删除标志',
   primary key (ID)
);

alter table ANT_PLAN_TEAM_GUIDE comment '团组领队申请表';
