drop table if exists ANT_PLAN_ORDER;

/*==============================================================*/
/* Table: ANT_PLAN_ORDER                                        */
/*==============================================================*/
create table ANT_PLAN_ORDER
(
   ID                   bigint not null auto_increment comment '主键',
   ORDER_NUMBER         varchar(50) comment '订单号',
   SCHEDULE_CODE        varchar(50) comment '班期编码',
   TRIP_CODE            varchar(50) comment '行程编码',
   TRIP_ID              varchar(50) comment '行程ID(产品ID)',
   PLAN_CODE            varchar(50) comment '方案编码',
   ORDER_CATEGORY       integer comment '订单类型 1-预订2-预留',
   RESERVE_TIME         datetime comment '预留截至时间 (只有状态为预留时存在)',
   DEPART_DATE_FROM     datetime comment '出行日期-从',
   DEPART_DATE_TO       datetime comment '出行日期-至',
   TOUR_NUMBER          varchar(50) comment '团号',
   FULL_TRIP_NAME       varchar(1000) comment '产品名称',
   PRODUCT_INFO         text comment '产品数据 JSON',
   SELLER_CODE          varchar(50) comment '销售商编码',
   SELLER_FULL_NAME     varchar(500) comment '销售商名称(客户名称)',
   SELLER_SHORT_NAME    varchar(500) comment '销售商简称',
   SELLER_FINA_NAME     varchar(500) comment '销售商财务简称',
   SELLER_FINA_NUMBER   varchar(50) comment '销售商财务编码',
   ORDER_CONTACT        text comment '订单联系人JSON',
   SALES_MAIN_CODE      varchar(50) comment '首席销售',
   SALES_ASSISTANT_CODE varchar(50) comment '助手销售',
   TOTAL_QUOTA          decimal(15,2) comment '售价组-合计-名额',
   TOTAL_BABY           decimal(15,2) comment '售价组-合计--婴儿',
   TOTAL_ROOM           decimal(15,2) comment '售价组-合计-用房',
   TOTAL_NUMBER         decimal(15,2) comment '售价组-合计-份数',
   TOTAL_ADDITIONAL_1   decimal(15,2) comment '售价组-合计-附加价1',
   TOTAL_ADDITIONAL_2   decimal(15,2) comment '售价组-合计-附加价2',
   TOTAL_ADDITIONAL_3   decimal(15,2) comment '售价组-合计-附加价3',
   TOTAL_ADDITIONAL_4   decimal(15,2) comment '售价组-合计-附加价4',
   TOTAL_ADDITIONAL_5   decimal(15,2) comment '售价组-合计-附加价5',
   TOTAL_ADDITIONAL_6   decimal(15,2) comment '售价组-合计-附加价6',
   TOTAL_OTHER          decimal(15,2) comment '其他-合计(保险、接送、wifi)',
   NAME_AGENT           varchar(1000) comment '内部金额-名称',
   NAME_SELLER          varchar(1000) comment '销售商金额-名称',
   NAME_TOURIST         varchar(1000) comment '游客金额-名称',
   ADJUST_AGENT_PRICE   decimal(15,2) comment '内部结算-调价',
   ADJUST_AGENT_REMARK  varchar(1000) comment '内部结算-调价-说明',
   ADJUST_SELLER_PRICE  decimal(15,2) comment '销售商结算(应收款)-调价',
   ADJUST_SELLER_REMARK varchar(1000) comment '销售商结算(应收款)-调价-说明',
   ADJUST_TOURIST_PRICE decimal(15,2) comment '游客金额-调价',
   ADJUST_TOURIST_REMARK varchar(1000) comment '游客金额-调价-说明',
   FORMULA_AGENT        varchar(2000) comment '内部金额-计算公式描述',
   FORMULA_SELLER       varchar(2000) comment '销售商金额-计算公式描述',
   FORMULA_TOURIST      varchar(2000) comment '游客金额-计算公式描述',
   RECEIVE_AGENT        decimal(15,2) comment '内部金额-已收款',
   RECEIVE_SELLER       decimal(15,2) comment '销售商金额-已收款',
   RECEIVE_TOURIST      decimal(15,2) comment '游客金额-已收款',
   UNPAID_AGENT         decimal(15,2) comment '内部金额-未收款',
   UNPAID_SELLER        decimal(15,2) comment '销售商金额-未收款',
   UNPAID_TOURIST       decimal(15,2) comment '游客金额-未收款',
   REFUND_AGENT         decimal(15,2) comment '内部金额-待退',
   REFUND_SELLER        decimal(15,2) comment '销售商金额-待退',
   TOTAL_AGENT          decimal(15,2) comment '内部金额-合计',
   TOTAL_SELLER         decimal(15,2) comment '销售商金额-合计',
   TOTAL_TOURIST        decimal(15,2) comment '游客金额-合计',
   PRICE_LOCATION       varchar(200) comment '应收款定位',
   REMARK               varchar(200) comment '备注',
   ORDER_USER_ID        varchar(50) comment '下单人员',
   ORDER_USER_TIME      datetime comment '下单时间',
   HOLD_USER_ID         varchar(50) comment '控位计调',
   UPDATE_USER_ID       varchar(50) comment '订单修改人员',
   UPDATE_USER_TIME     datetime comment '订单修改时间',
   CHECK_USER_ID        varchar(50) comment '审核人员',
   CHECK_USER_TIME      datetime comment '审核时间',
   CHECK_STATUS         integer comment '审核状态 0-未审 1-待审 2-已审 3-拒审',
   CHECK_REASON         text comment '审核原因',
   CREATE_TIME          datetime comment '创建时间',
   CREATE_ID            varchar(50) comment '创建者',
   MODIFY_TIME          datetime comment '修改时间',
   MODIFY_ID            varchar(50) comment '修改者',
   DELETE_FLAG          char comment '删除标志',
   primary key (ID)
);

alter table ANT_PLAN_ORDER comment '出境游订单表';
